### ISSUE TITLE
sample.download() causing OverflowError

### ISSUE THREAD

**Issue by audy** [onecodex/onecodex#273]
`onecodex` - version 0.5.6
`python3` - version 3.5.6

```python
sample = ocx.Samples.get("<uuid_goes_here>")

sample.download()
```

traceback:

```
Traceback (most recent call last):
  File "./fetch-samples.py", line 15, in <module>
    sample.download()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/onecodex/models/helpers.py", line 129, in download
    resp = requests.get(url_data["download_uri"], stream=True)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/requests_cache/core.py", line 132, in request
    **kwargs
  File "/home/ubuntu/.local/lib/python3.5/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/requests_cache/core.py", line 105, in send
    return send_request_and_cache_response()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/requests_cache/core.py", line 99, in send_request_and_cache_response
    self.cache.save_response(cache_key, response)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/requests_cache/backends/base.py", line 46, in save_response
    self.responses[key] = self.reduce_response(response), datetime.utcnow()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/requests_cache/backends/storage/dbdict.py", line 165, in __setitem__
    sqlite.Binary(pickle.dumps(item)))
  File "/home/ubuntu/.local/lib/python3.5/site-packages/requests_cache/backends/storage/dbdict.py", line 130, in __setitem__
    self.table_name, (key, item))
OverflowError: BLOB longer than INT_MAX bytes
```

**Comment by bcamarda** [comment]
Possibly a requests_cache library issue. Possibly a no-issue

**Comment by boydgreenfield** [comment]
@audy Believe it is `requests-cache` issue. Closing.
